/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.typingtanuki.locomotive;

import org.junit.jupiter.api.Test;

class InstallerTest {
    @Test
    void appHasAGreeting() {
//        Installer classUnderTest = new Installer();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
