/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.typingtanuki.locomotive;

import com.github.typingtanuki.locomotive.comm.InstallerServer;

import java.io.IOException;

/**
 * Main class to bypass the javafx checks
 */
public class Installer {
    public static void main(String[] args) {
        if (isRoot()) {
            startAdminNode(args);
        } else {
            startGUI(args);
        }
    }

    private static boolean isRoot() {
        return "root".equalsIgnoreCase(System.getProperty("user.name"));
    }

    private static void startAdminNode(String[] args) {
        if (args.length != 1) {
            throw new IllegalStateException("Wrong arguments passed to admin node.");
        }
        int port;
        try {
            port = Integer.parseInt(args[0]);
        } catch (NumberFormatException e) {
            throw new IllegalStateException("Wrong arguments passed to admin node.");
        }

        System.out.println("bouning bouning " + port);
        try {
            InstallerAdmin.start(port);
        } catch (IOException e) {
            System.out.println("qweqwe");
            e.printStackTrace();
        }
    }

    private static void startGUI(String[] args) {
        try {
            InstallerServer.start();

            InstallerMain.main(args);
            InstallerServer.stop();
        } catch (IOException | RuntimeException e) {
            System.err.println("Could not start node");
            e.printStackTrace(System.err);
            System.exit(10);
        }
    }
}
