/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.typingtanuki.locomotive;

public class Installer {
    public static void main(String[] args) {
        InstallerMain.main(args);
    }
}
